# Site settings
title: walksay
email: taodeng0704@gmail.com
description: travel suggestion
baseurl: 
url: www.walksay.com
github_username:  donkey13

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination

collections:
  travel:
    output: true
    permalink: /travel/:path/
  blog:
    output: true
    permalink: /blog/:path/


