# Site settings
title: walksay
email: taodeng0704@gmail.com
description: > # this means to ignore newlines until "baseurl:"
travel suggestion
baseurl:  # the subpath of your site, e.g. /blog/
url: www.walksay.com
github_username:  donkey13

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


